### ISSUE TITLE
Ajouter meetup cssflip

### ISSUE THREAD

**Issue by KBizien** [ndeloof/rennes.tech#3]
Hello,
Est-ce possible d'ajouter le groupe meetup cssflip ?
- [https://www.meetup.com/fr-FR/cssflip](https://www.meetup.com/fr-FR/cssflip)
- [https://cssflip.com](https://cssflip.com)

Logo : 
<img width="200" alt="logo" src="https://user-images.githubusercontent.com/6154884/38894296-1b9c816c-428d-11e8-8682-23b242c1c24a.png">

Belle initiative en tout cas ! 👍Si cela intéresse du monde, il y a un slack web@rennes où nous essayons également de transmettre et fédérer les différents événements rennais : 
[Slack web@rennes](https://webrennes.slack.com/join/shared_invite/enQtMjEwMzE3NjI2NDQ5LTMwY2YyNDczNzRhYzQyNGI0MmU5OGY0OGE5NzczODBmYTM5NjgxMDZlMjkxOTljNWZlMTA1MGY2YzNjYzUxMTg)

N'hésitez pas à le rejoindre et le partager à toutes personnes susceptibles d'être intéressées :)

Kevin.

**Comment by KBizien** [comment]
Ceci dit, je peux peut-être faire une MR et préparer cela ?

**Comment by ndeloof** [comment]
done, bienvenue dans la bande :P

**Comment by ndeloof** [comment]
Hello @KBizien. Concernant l'idée d'un slack permettant de fédérer les différents événements rennais nous avions déjà de notre côté eu la même idée. Sur le slack breizhcamp nous sommes 8 meetups par exemple, liés à la même association. Cependant @sergehardy a eu la bonne idée de créer un slack à part pour des discussions plus générales entre communautés techniques Rennaises : https://rennestech.slack.com
Est-ce que ça t'intéresse ? Aucunement l'intention de te couper l'herbe sous le pied, juste que "webrennes" me semble cibler une population "web/front" dans laquelle plusieurs meetups (dont le miens: docker-meetup) ne se reconnaitrons pas forcément. BREF, tu es le bienvenu si ça te tente.
